/*
 * Private Services API  - OpenAPI 3.0
 *
 * This is the set of api endpoints to support access to Subscripify Super Services. Super Services are those that are available to Subscripify super tenants. They provide higher capabilities to super tenants to manage across multiple main tenants within the context of the Super-Tenant.<br><br> These APIs act as the front end to Private Services engineered and hosted by super tenants that need to access the subscripify platform.<br><br>Examples of super services available only to Super Tenants through this API are- <br>Tenant Management<br>Subscription and Plan Management <br>Billing and Payments<br><br> Subscripify also maintains a set of api endpoints to support access to Subscripify Public Services. Subscripify public services are services required by all tenants and users on the subscripify platform. All tenants, regardless of type have access to these services.<br><br>Examples of private services available to Super Tenants and to Main Tenants are- <br>Identity Services<br>Usage Analytics Services<br>For more information about Subscripify tenant architecture click here.
 *
 * API version: 0.0.1
 * Contact: william.ohara@subscripify.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tenantapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddLordTenant",
		strings.ToUpper("Post"),
		"/lord-tenants",
		AddLordTenant,
	},

	Route{
		"AddTenant",
		strings.ToUpper("Post"),
		"/tenants",
		AddTenant,
	},

	Route{
		"DeleteTenant",
		strings.ToUpper("Delete"),
		"/tenants/{targetTenantUUID}",
		DeleteTenant,
	},

	Route{
		"GetTenant",
		strings.ToUpper("Get"),
		"/tenants/{targetTenantUUID}",
		GetTenant,
	},

	Route{
		"SearchTenant",
		strings.ToUpper("Get"),
		"/tenants/search",
		SearchTenant,
	},

	Route{
		"UpdateTenant",
		strings.ToUpper("Patch"),
		"/tenants/{targetTenantUUID}",
		UpdateTenant,
	},
}
